### ISSUE TITLE
Advantage over native promise hooks?

### ISSUE THREAD

**Issue by edborden** [danmcclain/ember-deferred-content#10]
I ran across this addon and I'm curious as to how this differs from using the native promise hooks, like so:
```
{{#if blogs.comments.isFulfilled}}
  {{#each blog.comments as |comment|}}
    // etc
  {{/each
{{/if}}

I do this already in many of my templates. What advantage does this plugin provide?

**Comment by danmcclain** [comment]
Those "native promise hooks" are come from Ember Data, not the promises themselves. If you have promise outside of ember data relationships, this addon will cover those cases (and also this works with the Ember Data promises, so you can have a consistent API regardless)

The way you get those hooks comes from `PromiseProxyMixin`: http://emberjs.com/api/classes/Ember.PromiseProxyMixin.html
