### ISSUE TITLE
Stuck in pending when returning `RSVP.resolve` from model hook

### ISSUE THREAD

**Issue by ryanlabouve** [danmcclain/ember-deferred-content#8]
When `RSVP.resolve` is returned from the model hook, somewhere along the way to the template it turns into just a POJO.

Here's an example twiddle twiddle: https://ember-twiddle.com/6365989705c325d944aaf911217b33c7?openFiles=routes.application.js%2C

I'd be happy to work on a solution for this? It could also solve the issue folks are having when they pass POJO's instead of promises (i.e. https://github.com/danmcclain/ember-deferred-content/issues/6)

**Comment by danmcclain** [comment]
Just a note: if people are passing the result of the model hook when they returned a promise in the model hook, this component will do nothing, that promise will be resolved already

**Comment by ryanlabouve** [comment]
Ah, that makes sense. 😅

Do you think this is still a valid use case for the component gracefully handling when it's passed a POJO instead of a promise. I think the two options could either be 1) have an assert method when it's not passed a promise initially or 2) be fine with POJO instead of promise and just put it in a resolved / fulfilled state?

**Comment by danmcclain** [comment]
I'm a bit impartial to the final implementation, whether we `RSVP.resolve` the initial object passed in or assert. I feel like assert is more correct (You don't need this component, you are already loaded), but then the coercion to a promise makes it easier for the dev

I think assert is the more correct the approach

**Comment by ryanlabouve** [comment]
Took a stab at it here: https://github.com/danmcclain/ember-deferred-content/pull/9

**Comment by danmcclain** [comment]
Closing since this was resolved! Thanks again
